pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    
        stage ("terraform init") {
            steps {
                sh '''
                cd terraform/postgresdb
                ls -l
                terraform init
                '''
            }
        }
        
        stage ("plan") {
            steps {
                sh '''
                cd terraform/postgresdb
                ls -l
                terraform plan -var "Env=$Env" -var="access_key=${access_key}" -var="secret_access_key=${secret_access_key}"
                '''
            }
        }

        stage ("Action") {
            steps {
                sh '''
                echo "Terraform action is --> ${action}"
                cd terraform/postgresdb
                ls -l
                terraform ${action} -auto-approve -var "Env=$Env" -var="access_key=${access_key}" -var="secret_access_key=${secret_access_key}"
                '''
           }
        }
    }
}
    
